// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebApplication2.Models
{
    public partial class Divisions
    {
        public int DivisionId { get; set; }
        public string DivisionName { get; set; }
    }
}